swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /movie:
    get:
      operationId: movie.read_all
      tags:
        - Movie
      summary: Read the entire list of movie
      description: Read the list of movie
      responses:
        200:
          description: Successfully read movie list operation
          schema:
            type: array
            items:
              properties:
                movie_id:
                  type: string
                popularity:
                  type: string
                director:
                  type: string
                genre:
                  type: string
                imdb_score:
                  type: string
                name:
                  type: string
    post:
      operationId: movie.create
      tags:
        - Movie
      summary: Create a movie and add it to the movie list
      description: Create a new movie in the movie list
      parameters:
        - name: movie
          in: body
          description: Person to create
          required: True
          schema:
            type: object
            properties:
              popularity:
                type: string
              director:
                type: string
              genre:
                type: string
              imdb_score:
                type: string
              name:
                type: string
      responses:
        201:
          description: Successfully created movie in list

  /movie/{movie_id}:
      get:
        operationId: movie.read_one
        tags:
          - Movie
        summary: Read one movie from the movie list
        description: Read one movie from the movie list
        parameters:
          - name: movie_id
            in: path
            description: Movie Id of the movie to get details from the list
            type: integer
            required: True
        responses:
          200:
            description: Successfully read movie from movie list operation
            schema:
              properties:
                movie_id:
                  type: string
                popularity:
                  type: string
                director:
                  type: string
                genre:
                  type: string
                imdb_score:
                  type: string
                name:
                  type: string

      put:
        operationId: movie.update
        tags:
          - Movie
        summary: Update a movie in the movie list
        description: Update a movie in the movie list
        parameters:
          - name: movie_id
            in: path
            description: Update all fields of the movie to alter in the list
            type: integer
            required: True
          - name: movie
            in: body
            schema:
              type: object
              properties:
                popularity:
                  type: string
                director:
                  type: string
                genre:
                  type: string
                imdb_score:
                  type: string
                name:
                  type: string
        responses:
          200:
            description: Successfully updated movie in movie list
      delete:
        operationId: movie.delete
        tags:
          - Movie
        summary: Delete a movie from the movie list
        description: Delete a movie
        parameters:
          - name: movie_id
            in: path
            type: integer
            required: True
        responses:
          200:
            description: Successfully deleted a movie from movie list

  /movie/search:
    post:
      operationId: movie.search
      tags:
        - Movie
      summary: Search a movie from the movie list
      description: Search a movie in the movie list using combined parameters
      parameters:
        - name: movie
          in: body
          description: Movie to search
          required: True
          schema:
            type: object
            properties:
              movie_id:
                type: string
              popularity:
                type: string
              director:
                type: string
              genre:
                type: string
              imdb_score:
                type: string
              name:
                type: string
      responses:
        201:
          description: Successfully searched movie in the list
