swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /movie:
    get:
      operationId: movie.read_all
      tags:
        - Movie
      summary: Read the entire list of people
      description: Read the list of people
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of people to get from people
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering people
          required: false
      responses:
        200:
          description: Successfully read people list operation
          schema:
            type: array
            items:
              properties:
                movie_id:
                  type: string
                popularity:
                  type: string
                director:
                  type: string
                genre:
                  type: string
                imdb_score:
                  type: string
                name:
                  type: string
    post:
      operationId: movie.create
      tags:
        - Movie
      summary: Create a person and add it to the people list
      description: Create a new person in the people list
      parameters:
        - name: movie
          in: body
          description: Person to create
          required: True
          schema:
            type: object
            properties:
              popularity:
                type: string
              director:
                type: string
              genre:
                type: string
              imdb_score:
                type: string
              name:
                type: string
      responses:
        201:
          description: Successfully created person in list

  /movie/{movie_id}:
      get:
        operationId: movie.read_one
        tags:
          - Movie
        summary: Read one person from the people list
        description: Read one person from the people list
        parameters:
          - name: movie_id
            in: path
            description: Last name of the person to get from the list
            type: integer
            required: True
        responses:
          200:
            description: Successfully read person from people list operation
            schema:
              properties:
                movie_id:
                  type: string
                popularity:
                  type: string
                director:
                  type: string
                genre:
                  type: string
                imdb_score:
                  type: string
                name:
                  type: string

      put:
        operationId: movie.update
        tags:
          - Movie
        summary: Update a person in the people list
        description: Update a person in the people list
        parameters:
          - name: movie_id
            in: path
            description: Last name of the person to update in the list
            type: integer
            required: True
          - name: movie
            in: body
            schema:
              type: object
              properties:
                popularity:
                  type: string
                director:
                  type: string
                genre:
                  type: string
                imdb_score:
                  type: string
                name:
                  type: string
        responses:
          200:
            description: Successfully updated person in people list
      delete:
        operationId: movie.delete
        tags:
          - Movie
        summary: Delete a person from the people list
        description: Delete a person
        parameters:
          - name: movie_id
            in: path
            type: integer
            required: True
        responses:
          200:
            description: Successfully deleted a person from people list
