# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-20 08:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190720_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 20, 8, 22, 17, 544752, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 20, 8, 22, 17, 542750, tzinfo=utc)),
        ),
    ]
