# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-20 10:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190720_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 20, 10, 36, 26, 14726, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 20, 10, 36, 26, 15727, tzinfo=utc)),
        ),
    ]
